name       : libgnome-desktop
version    : 3.20.2
release    : 13
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-desktop/3.20/gnome-desktop-3.20.2.tar.xz : 492c2da7aa8c3a8b65796e8171fc8f0dfb5d322dd2799c0d76392e1fb061e2b2
homepage   : http://www.gnome.org/
license    :
    - LGPL-2.1
summary    : GNOME utility runtime library
builddeps  :
    - pkgconfig(xkeyboard-config)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xkbfile)
    - itstool
component  : desktop.gnome.core
description: |
    GNOME utility runtime library
setup      : |
    %configure --libexecdir=%libdir%/GnomeDesktop \
               --with-gnome-distributor=\"Solus\" \
               --disable-static
build      : |
    %make
install    : |
    %make_install
