name       : libgnome-desktop
version    : 3.26.1
release    : 17
source     :
    - https://download.gnome.org/sources/gnome-desktop/3.26/gnome-desktop-3.26.1.tar.xz : 92fa697af986fb2c6bc6595f0155c968c17e5d1981a50584ff4fb6fd60124e2f
homepage   : http://www.gnome.org/
license    : LGPL-2.1
component  : desktop.gnome.core
summary    : GNOME utility runtime library
description: |
    GNOME utility runtime library
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libseccomp)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - itstool
setup      : |
    %configure --libexecdir=%libdir%/GnomeDesktop \
               --with-gnome-distributor=\"Solus\" \
               --disable-static
build      : |
    %make
install    : |
    %make_install
