name       : libgnome-desktop
version    : 3.22.2
release    : 14
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-desktop/3.22/gnome-desktop-3.22.2.tar.xz : 51d7ebf7a6c359be14c3dd7a022213e931484653815eb10b0131bef4c8979e1c
homepage   : http://www.gnome.org/
license    :
    - LGPL-2.1
summary    : GNOME utility runtime library
builddeps  :
    - pkgconfig(xkeyboard-config)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xkbfile)
    - itstool
component  : desktop.gnome.core
description: |
    GNOME utility runtime library
setup      : |
    %configure --libexecdir=%libdir%/GnomeDesktop \
               --with-gnome-distributor=\"Solus\" \
               --disable-static
build      : |
    %make
install    : |
    %make_install
