name       : libgnome-desktop
version    : 3.24.1
release    : 16
source     :
    - https://download.gnome.org/sources/gnome-desktop/3.24/gnome-desktop-3.24.1.tar.xz : de09b7d38b4baccae48c527778480731cb12f00848758be186971b2b4acc45ab
homepage   : http://www.gnome.org/
license    : LGPL-2.1
component  : desktop.gnome.core
summary    : GNOME utility runtime library
description: |
    GNOME utility runtime library
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - itstool
setup      : |
    %configure --libexecdir=%libdir%/GnomeDesktop \
               --with-gnome-distributor=\"Solus\" \
               --disable-static
build      : |
    %make
install    : |
    %make_install
