name       : libgnome-desktop
version    : 3.28.2
release    : 22
source     :
    - https://download.gnome.org/sources/gnome-desktop/3.28/gnome-desktop-3.28.2.tar.xz : 605087bff17c61bc167ccb5a61ed4d06eab922fcce384576ed2a3577214c8330
homepage   : http://www.gnome.org/
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : GNOME utility runtime library
description: |
    GNOME utility runtime library
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libseccomp)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - itstool
rundeps    :
    - bubblewrap
setup      : |
    %configure --libexecdir=%libdir%/GnomeDesktop \
               --with-gnome-distributor=\"Solus\" \
               --disable-static
build      : |
    %make
install    : |
    %make_install
