name       : libgnome-desktop
version    : '43'
release    : 54
source     :
    - https://download.gnome.org/sources/gnome-desktop/43/gnome-desktop-43.tar.xz : 3d6e153317486157596aa3802f87676414c570738f450a94a041fe8835420a69
homepage   : http://www.gnome.org/
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : GNOME utility runtime library
description: |
    GNOME utility runtime library
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk4)
    - pkgconfig(libseccomp)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - gtk-doc
    - itstool
rundeps    :
    - bubblewrap
setup      : |
    %meson_configure -Dbuild_gtk4=true -Dlegacy_library=true -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
