name       : libgnome-desktop
version    : 3.26.2
release    : 19
source     :
    - https://download.gnome.org/sources/gnome-desktop/3.26/gnome-desktop-3.26.2.tar.xz : f7561a7a313fc474b2c390cd9696df1f5c1e1556080e43f4afe042b1060e5f2a
homepage   : http://www.gnome.org/
license    : LGPL-2.1
component  : desktop.gnome.core
summary    : GNOME utility runtime library
description: |
    GNOME utility runtime library
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libseccomp)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - itstool
rundeps    :
    - bubblewrap
setup      : |
    %configure --libexecdir=%libdir%/GnomeDesktop \
               --with-gnome-distributor=\"Solus\" \
               --disable-static
build      : |
    %make
install    : |
    %make_install
