name       : libgnome-desktop
version    : 3.38.1
release    : 37
source     :
    - https://download.gnome.org/sources/gnome-desktop/3.38/gnome-desktop-3.38.1.tar.xz : 17903513fed60814e967512dd892751cb6a1d2716136232884bc65bd53cc3be0
homepage   : http://www.gnome.org/
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : GNOME utility runtime library
description: |
    GNOME utility runtime library
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libseccomp)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - gtk-doc
    - itstool
rundeps    :
    - bubblewrap
setup      : |
    %meson_configure -Dgnome_distributor="Solus" -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
