name       : libgnome-desktop
version    : 3.34.4
release    : 30
source     :
    - https://download.gnome.org/sources/gnome-desktop/3.34/gnome-desktop-3.34.4.tar.xz : c53e72737cc21535f2fd4b72bc2fb5594741cfc3d3ce90949bc5cc07bade0cbc
homepage   : http://www.gnome.org/
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : GNOME utility runtime library
description: |
    GNOME utility runtime library
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libseccomp)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - gtk-doc
    - itstool
rundeps    :
    - bubblewrap
setup      : |
    %meson_configure -Dgnome_distributor="Solus" -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
