name       : libgnome-desktop
version    : 3.36.3.1
release    : 34
source     :
    - https://download.gnome.org/sources/gnome-desktop/3.36/gnome-desktop-3.36.3.1.tar.xz : 4bed119fa25ea0ff7880928142365c3c8726585fc072bc147157e66b63e96b7e
homepage   : http://www.gnome.org/
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : GNOME utility runtime library
description: |
    GNOME utility runtime library
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libseccomp)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - gtk-doc
    - itstool
rundeps    :
    - bubblewrap
setup      : |
    %patch -p1 < $pkgfiles/0001-Revert-libgnome-desktop-gnome-bg.c-Remove-API-that-d.patch
    %meson_configure -Dgnome_distributor="Solus" -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
