name       : libgnome-desktop
version    : 3.38.4
release    : 40
source     :
    - https://download.gnome.org/sources/gnome-desktop/3.38/gnome-desktop-3.38.4.tar.xz : 3f603ea5bfd47722c92cfc9b885446b46260ea09c8cfb63f6bdd9fefe342e48c
homepage   : http://www.gnome.org/
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : GNOME utility runtime library
description: |
    GNOME utility runtime library
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libseccomp)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - gtk-doc
    - itstool
rundeps    :
    - bubblewrap
setup      : |
    %meson_configure -Dgnome_distributor="Solus" -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
