name       : libgnome-desktop
version    : '40.0'
release    : 41
source     :
    - https://download.gnome.org/sources/gnome-desktop/40/gnome-desktop-40.0.tar.xz : 20abfd3f831e4e8092b55839311661dc73b2bf13fc9bef71c4a5a4475da9ee04
homepage   : http://www.gnome.org/
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : GNOME utility runtime library
description: |
    GNOME utility runtime library
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libseccomp)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - gtk-doc
    - itstool
rundeps    :
    - bubblewrap
setup      : |
    %meson_configure -Dgnome_distributor="Solus" -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
